- name: Clone st repo locally.
  git:
    repo: "{{ st_repo }}"
    dest: "{{ st_repo_local_destination }}"
    version: "{{ st_repo_version }}"
    accept_hostkey: "{{ st_repo_accept_hostkey }}"
  become: false
  register: st_repo

- name: Install dependencies
  apt:
    name: "{{ item }}"
  become: true
  with_items: "{{ st_dependencies }}"

- name: Install st
  shell: |
    make install
  args:
    chdir: "{{ st_repo_local_destination }}"
    creates: "{{ (st_repo.changed == true or st_force_install == true) | ternary('/usr/local/bin/st_dummy', '/usr/local/bin/st') }}"
  become: true

- name: Install JetBrains Mono Fonts
  block:
    - name: Ensure fonts directory
      file:
        path: "{{ ansible_env.HOME }}/.local/share/fonts"
        state: directory
        recurse: true

    - name: Install fontconfig
      ansible.builtin.package:
        name:
          - fontconfig

    - name: Install JetBrains Mono typeface
      unarchive:
        creates: "{{ ansible_env.HOME }}/.local/share/fonts/fonts/ttf/JetBrainsMono-*"
        src: "https://github.com/JetBrains/JetBrainsMono/releases/download/v2.242/JetBrainsMono-2.242.zip"
        remote_src: true
        dest: "{{ ansible_env.HOME }}/.local/share/fonts"
      notify: "refresh font cache"

- include_tasks: ./patch_libxft.yml
  when: st_patch_libxft == true

- name: Set ST as default terminal emulator
  # update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/local/bin/st 0
  alternatives:
    name: x-terminal-emulator
    path: /usr/local/bin/st
    priority: 0
  become: true
  when: st_default_terminal_emulator == true
