- name: Clone libxft-bgra repo locally.
  git:
    repo: "https://github.com/uditkarode/libxft-bgra"
    dest: "{{ st_patch_libxft_destination }}"
    version: "master"
  become: false

- name: Autogen libxft-bgra
  shell: ./autogen.sh --sysconfdir=/etc --prefix=/usr --mandir=/usr/share/man
  args:
    chdir: "{{ st_patch_libxft_destination }}"
    creates: "{{ st_patch_libxft_destination }}/configure"

- name: Install libxft
  make:
    chdir: "{{ st_patch_libxft_destination }}"
    target: install
  become: true
