# This is required to have BGRA glyph support, which got merged upstream in: https://gitlab.freedesktop.org/xorg/lib/libxft/-/merge_requests/12
# It took ages for this patch to get merged upstream and it used to only live in: "https://github.com/uditkarode/libxft-bgra"
# I switched to using the master version of libxft from freedesktop. I'll pin it to a version that includes the patch once they
# push out a new version after 2.3.4
# I will need to include this patch until upstream distros start installing a version after 2.3.4

- name: Install xft build dependencies
  apt:
    pkg:
      - autoconf
      - xutils-dev
      - libtool
  become: true

- name: Clone libxft-bgra repo locally.
  git:
    repo: "https://gitlab.freedesktop.org/xorg/lib/libxft.git"
    dest: "{{ st_patch_libxft_destination }}"
    version: "master"
  become: false

- name: Autogen libxft-bgra
  shell: ./autogen.sh --sysconfdir=/etc --prefix=/usr --mandir=/usr/share/man
  args:
    chdir: "{{ st_patch_libxft_destination }}"
    creates: "{{ st_patch_libxft_destination }}/configure"

- name: Install libxft
  make:
    chdir: "{{ st_patch_libxft_destination }}"
    target: install
  become: true

- name: Check type of /lib/x86_64-linux-gnu/libXft.so.2.3.4
  stat:
    path: /lib/x86_64-linux-gnu/libXft.so.2.3.4
  register: libxft

- name: Backup original libXft.so.2.3.4
  copy:
    src: /lib/x86_64-linux-gnu/libXft.so.2.3.4
    dest: /lib/x86_64-linux-gnu/libXft.so.2.3.4.backup
  become: true
  when: "libxft.stat.isreg == true"

- name: Patch libxft library
  file:
    src: /usr/lib/libXft.so.2.3.4
    dest: /lib/x86_64-linux-gnu/libXft.so.2.3.4
    state: link
    force: true
  become: true

- name: Patch libxft library
  file:
    src: /lib/x86_64-linux-gnu/libXft.so.2.3.4
    dest: /lib/x86_64-linux-gnu/libXft.so.2
    state: link
    force: true
  become: true
