- name: Ensure ZSH installed
  apt:
    name: zsh
  become: true
  when: ansible_os_family == "Debian"

- name: Ensure zsh installed Mac
  shell: brew install zsh
  creates: /usr/local/bin/zsh
  when: ansible_os_family == "Darwin"

- name: Install Oh My ZSH
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ zsh_dot_dir }}/oh-my-zsh"
    clone: true
    update: true

- name: Install ZSH Plugins
  git:
    repo: "https://github.com/zsh-users/{{ item }}.git"
    dest: "{{ zsh_dot_dir }}/custom/plugins/{{ item }}"
    clone: true
    update: true
  with_items: "{{ zsh_plugins }}"

- name: Set ZSH as the default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true
  when: zsh_default_shell == true
