- name: Ensure tmux installed
  apt:
    name: tmux
  become: true
  when: ansible_os_family == "Debian"

- name: Ensure tmux installed Mac
  shell: brew install tmux
  creates: /usr/local/bin/tmux
  when: ansible_os_family == "Darwin"

- name: Install TPM (Tmux Plugin Manager)
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ tmux_dot_dir }}/plugins/tpm"
    clone: true
    update: true

- name: Refresh tmux plugins
  shell: |
    {{ tmux_dot_dir }}/plugins/tpm/bin/install_plugins
    {{ tmux_dot_dir }}/plugins/tpm/bin/update_plugins all
  environment:
    TMUX_PLUGIN_MANAGER_PATH: "{{ tmux_dot_dir }}/plugins"
