- name: Inatall NeoVim
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim.appimage"
    dest: "{{ ansible_env.HOME }}/.local/bin/nvim"
    checksum: "sha256:https://github.com/neovim/neovim/releases/download/{{ neovim_version }}/nvim.appimage.sha256sum"
    mode: 0744
